### ISSUE TITLE
How can I get the prediction result?

### ISSUE THREAD

**Issue by Roxyi** [alasdairtran/radflow#3]
There are examples about training and evaluating, but I didn't find the way of getting the prediction result. Can you show me how to do that? Also, on line 899 in radflow.py where you define the predict function, it seems that the reference to X is missing.

**Comment by alasdairtran** [comment]
After you call the `radflow evaluate` command, a new file `evaluate-metrics.json` will be created in the `serialization` directory. The raw predictions are stored there. For example, if you have downloaded our `expt` directory, you can access the predictions from the one-hop dynamic network model on the Vevo dataset like this:

```python
import json

path = 'expt/network_aggregation/vevo_dynamic/forecast/one_hop/15_radflow/serialization/evaluate-metrics.json'
with open(path) as f:
    obj = json.load(f)

preds = obj['preds']

# In the Vevo test split, we have 13710 examples
assert len(obj['preds']) == 13710

# And for each test example, we predict 7 steps in ahead
assert len(obj['preds'][0]) == 7
```

The part of the code that stores the predictions is [here](https://github.com/alasdairtran/radflow/blob/71d93d9a134ff260159e45f39b1cdee7fa9be997/radflow/models/radflow.py#L857), which only runs during evaluation and testing.

> on line 899 in radflow.py where you define the predict function, it seems that the reference to X is missing.

My bad. That `X` is supposed to be `backcast`. I've pushed [a small fix](https://github.com/alasdairtran/radflow/commit/4ce6a65cf3fea177027364d5805d59c26ee1b032). But I haven't tested the `predict` function properly (it might not handle all edge cases). I think I was halfway through implementing that `predict` function because I wanted to create a live demo, but I then got busy with other things.

**Comment by Roxyi** [comment]
@alasdairtran Thank you very much! I find it difficult to debug using the command line tool and prefer to train and evaluate the model from a Python script directly in IDE like Pycharm. I'm trying to do something like the code below:
```python
model = RADflow(agg_type='attention',
                              forecast_length=28,
                              backcast_length=56,
                              test_lengths=[28],
                              peek=True,
                              data_path='my_data.h5'
                    )

dataloader = DataLoader(data, batch_size=batch_size, shuffle=True)

trainer = ApexGradientDescentTrainer(model=model, optimizer=torch.optim.Adam(model.parameters(), lr=0.001, betas=(0.9, 0.999)), DataLoader=dataloader)

metrics = trainer.train()
```
I'm not sure if that's the correct way. Besides, I have some other questions:

1. In the code above, I guess the data used to construct a torch DataLoader is a list of dictionaries of keys and splits and I can use the same code in the TaxiReader to create such a list based on my own data. Correct me if I am wrong about it.
2. If I set `peek=True`, do I need to train the model twice so that the neighbor embeddings learned in the first training can be used in the second round?

**Comment by alasdairtran** [comment]
Yep your code snippet looks good - you can initialise the model, dataloader, and trainer manually instead of using CLI and config files.

>  I guess the data used to construct a torch DataLoader is a list of dictionaries of keys

Yep if you look at my TaxiReader code, I return a list of `Instance` objects, each of which is basically a dictionary containing various fields like `x` and `y`. You can create your own `Dataset` object that yields these `Instance` objects, and then create your own `DataLoader` from it.

> If I set peek=True, do I need to train the model twice

It depends. If you don't give it a pretrained time-series model, then we'd be in the imputation setting, where we simply use the ground-truth future values of the neighbors. If you do give it a pretrained model, then we'd be in the forecast setting. The paper describes these two settings in more detail.

Note how in [my code](https://github.com/alasdairtran/radflow/blob/4ce6a65cf3fea177027364d5805d59c26ee1b032/radflow/models/radflow.py#L190), the parameters `base_model_config` and `base_model_weights` are used to initialise the pretrained model. And if it's provided, we replace the ground-truth views with the predicted views [here](https://github.com/alasdairtran/radflow/blob/4ce6a65cf3fea177027364d5805d59c26ee1b032/radflow/models/radflow.py#L435).

**Comment by Roxyi** [comment]
@alasdairtran Got it. Thank you!
